### PR TITLE
fix(legacy): celery manager

### LINKED ISSUE #1636: Cannot import any podcast episodes
**Describe the bug**
Selecting a podcast episode and clicking the Import button produces no result. Reloading the podcast list shows a perpetual spinning wheel next to the episode, even days later. 
Immediately after clicking import, network console shows a POST request returned 400 (“an unknown error occurred”). I think the request is supposed to create the podcast episode placeholder on the server.
The legacy.log file shows:
```
2022-02-10T15:07:03-08:00 ERR (3): libretime.cjly.net [ThirdPartyCeleryService.php:37 - _executeTask()] - Invalid request: Unknown extension name unknown
2022-02-10T15:07:03-08:00 ERR (3): libretime.cjly.net [PodcastEpisodesController.php:122 - postAction()] - Unknown extension name unknown
```
I have tried this with 8 different podcasts, all with the same result. 

**To Reproduce**
1. Go to 'Podcasts'
2. Add a podcast RSS feed
3. Double click the podcast to edit it
4. Click the check box next to an episode and click "Import"

**Expected behavior**
The podcast should finish downloading after a few minutes. 

**LibreTime version:**
From the installer: 07c0029d6
From libretime-api: 3.2.12

**Installation method:**
- Installed on two different servers; one physical machine and one Linode VPS. Both exhibited the same problem. 
- OS: Ubuntu 20.04 LTS
- Method: ./install script

**Client:**
- OS: Ubuntu
- Browser: Tried both Firefox and Chrome, latest versions

**Additional Context:**
On the server, the exception (“Unknown extension name unknown”) that is caught by the postAction() method of the Rest_PodcastEpisodesController appears to originate with the GetConcreteByName() method of the AbstractAMQPConnector. The name that has been given to the method is literally the string “unknown”.
On my first installation this exception appears in zendphp.log. In the latest installation it appears in legacy.log

Here is an example of a failed POST request:
```
{“csrf_token”:“059869b64ff194ad0789364f567a6c5dc42db81f”,“episode”:{“podcast_id”:5,“guid”:“37207 at https://www.thisamericanlife.org/”,“ingested”:0,“title”:“466: Blackjack”,“author”:“This American Life”,“description”:"The casino game everyone thinks they can beat. ",“pub_date”:“20 February 2022, 11:00 pm”,“link”:“[https://dts.podtrac.com/redirect.mp3/chtbl.com/track/8DB4DB/pdst.fm/e/nyt.simplecastaudio.com/bbbcc290-ed3b-44a2-8e5d-5513e38cfe20/episodes/b23011fa-15d2-4bd0-82b5-9f6c56b4d25e/audio/128/default.mp3?awCollectionId=bbbcc290-ed3b-44a2-8e5d-5513e38cfe20&awEpisodeId=b23011fa-15d2-4bd0-82b5-9f6c56b4d25e",“enclosure”:{“bitrate”:null,“captions”:null,“categories”:[{“term”:null,“scheme”:“http://www.itunes.com/dtds/podcast-1.0.dtd”,“label”:"Society](https://dts.podtrac.com/redirect.mp3/chtbl.com/track/8DB4DB/pdst.fm/e/nyt.simplecastaudio.com/bbbcc290-ed3b-44a2-8e5d-5513e38cfe20/episodes/b23011fa-15d2-4bd0-82b5-9f6c56b4d25e/audio/128/default.mp3?awCollectionId=bbbcc290-ed3b-44a2-8e5d-5513e38cfe20&awEpisodeId=b23011fa-15d2-4bd0-82b5-9f6c56b4d25e%22,%22enclosure%22:%7B%22bitrate%22:null,%22captions%22:null,%22categories%22:%5B%7B%22term%22:null,%22scheme%22:%22http://www.itunes.com/dtds/podcast-1.0.dtd%22,%22label%22:%22Society) & Culture”,“type”:null},{“term”:null,“scheme”:“[http://www.itunes.com/dtds/podcast-1.0.dtd",“label”:“Arts”,“type”:null},{“term”:null,“scheme”:“http://www.itunes.com/dtds/podcast-1.0.dtd”,“label”:“News”,“type”:null},{“term”:null,“scheme”:“http://www.itunes.com/dtds/podcast-1.0.dtd”,“label”:“Politics”,“type”:null}],“channels”:null,“copyright”:null,“credits”:null,“description”:null,“duration”:3784,“expression”:null,“framerate”:null,“handler”:“mp3”,“hashes”:null,“height”:null,“javascript”:null,“keywords”:null,“lang”:null,“length”:null,“link”:“https://dts.podtrac.com/redirect.mp3/chtbl.com/track/8DB4DB/pdst.fm/e/nyt.simplecastaudio.com/bbbcc290-ed3b-44a2-8e5d-5513e38cfe20/episodes/b23011fa-15d2-4bd0-82b5-9f6c56b4d25e/audio/128/default.mp3?awCollectionId=bbbcc290-ed3b-44a2-8e5d-5513e38cfe20&awEpisodeId=b23011fa-15d2-4bd0-82b5-9f6c56b4d25e”,“medium”:null,“player”:null,“ratings”:null,“restrictions”:[{“relationship”:“allow”,“type”:null,“value”:“default”}],“samplingrate”:null,“thumbnails”:null,“title”:null,“type”:“audio/mpeg”,“width”:null},“file”:[],“importIcon”:"](http://www.itunes.com/dtds/podcast-1.0.dtd%22,%22label%22:%22Arts%22,%22type%22:null%7D,%7B%22term%22:null,%22scheme%22:%22http://www.itunes.com/dtds/podcast-1.0.dtd%22,%22label%22:%22News%22,%22type%22:null%7D,%7B%22term%22:null,%22scheme%22:%22http://www.itunes.com/dtds/podcast-1.0.dtd%22,%22label%22:%22Politics%22,%22type%22:null%7D%5D,%22channels%22:null,%22copyright%22:null,%22credits%22:null,%22description%22:null,%22duration%22:3784,%22expression%22:null,%22framerate%22:null,%22handler%22:%22mp3%22,%22hashes%22:null,%22height%22:null,%22javascript%22:null,%22keywords%22:null,%22lang%22:null,%22length%22:null,%22link%22:%22https://dts.podtrac.com/redirect.mp3/chtbl.com/track/8DB4DB/pdst.fm/e/nyt.simplecastaudio.com/bbbcc290-ed3b-44a2-8e5d-5513e38cfe20/episodes/b23011fa-15d2-4bd0-82b5-9f6c56b4d25e/audio/128/default.mp3?awCollectionId=bbbcc290-ed3b-44a2-8e5d-5513e38cfe20&awEpisodeId=b23011fa-15d2-4bd0-82b5-9f6c56b4d25e%22,%22medium%22:null,%22player%22:null,%22ratings%22:null,%22restrictions%22:%5B%7B%22relationship%22:%22allow%22,%22type%22:null,%22value%22:%22default%22%7D%5D,%22samplingrate%22:null,%22thumbnails%22:null,%22title%22:null,%22type%22:%22audio/mpeg%22,%22width%22:null%7D,%22file%22:%5B%5D,%22importIcon%22:%22)”}}
```

### PR DESCRIPTION
**Pull request by jooola**
Fixes #1636 

I hope this helps with #1241 and #1084

### CODE REVIEW

File: legacy/application/common/CeleryManager.php [hunk 1]
```diff
@@ -38,12 +42,11 @@ private static function _setupCeleryExchange($config, $exchange, $queue)
...
             $config['rabbitmq']['password'],
             $config['rabbitmq']['vhost'],
-            $exchange,                        // Exchange name
-                          $queue,                           // Binding/queue
-                          $config['rabbitmq']['port'],
+            $exchange,
+            $queue,
+            $config['rabbitmq']['port'],
             false,
-            true,                             // Persistent messages
```
Comment (paddatrapper) [inline legacy/application/common/CeleryManager.php:45]: Was removing this parameter intentional?

Comment (jooola) [reply legacy/application/common/CeleryManager.php:45]: Yup: https://github.com/jooola/celery-php/blob/master/CHANGELOG.md
